### ISSUE TITLE
Build an hourweekday bin 'regressor' 

### ISSUE THREAD

**Issue by thoyt** [CenterForTheBuiltEnvironment/mave-app#6]
Use this crude model when the fancy ones fail.

**Comment by praftery** [comment]
Exactly. I figure we copy the structure of scikit learn and create a simple hour/weekday/oat regressor that works with a fit() method. That way we can use the existing cross-validation tools that come with sci-kit learn and don't need to reinvent the wheel.

**Comment by thoyt** [comment]
What does the model do for data outside of the oat training set? I will probably just start by creating the hour/weekday binned model.

**Comment by thoyt** [comment]
Got this far at least!

![figure_1](https://cloud.githubusercontent.com/assets/545954/5020235/f4b1d3e6-6a7b-11e4-9333-4b8589d3b888.png)

**Comment by thoyt** [comment]
8db3473bd4ed1c7740c86d63c47a27367e7a6104

Give it a whirl. I realized the obvious and extended DummyRegressor to make the binned estimator work with grid search. Using the median seems to produce almost exactly the same results. When I ran it, the model performed pretty respectably but still not as well as the fancy ones.

**Comment by praftery** [comment]
A couple of thoughts:
1) our worst case scenario needs to actually work if we encounter that scenario
2) it would be nice for there to be a printed & logged warning if we do end up decided that day/hour binning is the best method.

**Comment by thoyt** [comment]
Was just pondering how to take care of 1. It might be to transform the normalized timestamps in the estimator instead of passing in the unstandardized data. It might be least gross option.

As for 2, should we just always log which model was the best?

**Comment by praftery** [comment]
I think that solution works best, as long as it's relatively easy to do.

For 2, I just realized that it already logs which model was best as an info message - maybe this should be more along the lines of a warning? 

At the moment it looks like this in the log file:
=== Evaluating results ===
-- Best model parameters
ExtraTreesRegressor(bootstrap=False, compute_importances=None,
          criterion='mse', max_depth=None, max_features=5,
          max_leaf_nodes=None, min_density=None, min_samples_leaf=25,
          min_samples_split=30, n_estimators=45, n_jobs=1, oob_score=False,
          random_state=None, verbose=0)

**Comment by thoyt** [comment]
d91d3c54a2a715e326643e2ec17f6600a59eebbb

Should work now. One other thing I want to look at is whether the model still works if there are nans. It spits out warnings but seems to be able to do predictions anyway.

**Comment by praftery** [comment]
Hmmm. When I ran it on cbe_08.csv I got a bunch of warnings for the binning regressor and the results look strange. How about passing the X_standardizer and y_standardizer objects and using inbuilt transform and inverse_transform methods that the rest of the code uses?

**Comment by praftery** [comment]
The more I think about this, the less I like this solution of transforming the data back and forth unnecessarily. Maybe it's best to handle this using the added 'standardized' arg approach you had last time, and then manage the different predictions at the end?

**Comment by thoyt** [comment]
Yeah, those are the warnings I was talking about. It tries to divide when doing the mean and just gives warnings when it divides by zero. Whether the results look weird or not depends on which model they come up with after the grid search. Having nan's in the model is actually correct, but when predicting it will output nans, which is bad. Maybe some interpolation would do the trick.

I tried to pass the standardizer to the estimator without success.. the variable would always be None in the estimator, I thought it might have had something to do with the multithreading in some way

**Comment by thoyt** [comment]
There are always 4 warnings, probably when the the training set doesn't have any values for a certain hour and day. But then the model comes out ok for me (commented out the others)
![figure_1](https://cloud.githubusercontent.com/assets/545954/5053509/fc9babd8-6bff-11e4-91ee-a379901f9dd1.png)
:

**Comment by thoyt** [comment]
Something crazy happens to the other regressors when you use the binned estimator.. so there is some side-effect happening. Weird. Maybe we do need more structure after all.

**Comment by thoyt** [comment]
6ee6b812a8b30367b64932cec8a203555c3b7f0f

Well that threw me for a loop. I forgot that numpy arrays are always passed by reference so you have to be a little careful
